name: Tag latest and upload module assets

on:
  release:
    types: [published]

jobs:
  update-latest-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git user for tagging
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create or update 'latest' tag
        run: |
          git tag -f latest ${{ github.event.release.tag_name }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin --force --tags

      - name: Create module.zip (analog GitHub source archive)
        run: |
          mkdir temp-release
          git archive --format=zip --output=temp-release/module.zip HEAD

      - name: Upload module.json and module.zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            module.json
            temp-release/module.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
