name: Tag latest and upload module assets

on:
  push:
    branches:
      - main
      - master

jobs:
  update-latest-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git user for tagging
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create or update 'latest' tag
        run: |
          # Create a tag name based on commit SHA and timestamp
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)
          TAG_NAME="latest-${TIMESTAMP}-${COMMIT_SHA_SHORT}"
          
          # Create the new tag
          git tag -f latest ${{ github.sha }}
          git tag -f $TAG_NAME ${{ github.sha }}
          
          # Push tags to remote
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin --force --tags

      - name: Create module.zip (analog GitHub source archive)
        run: |
          mkdir temp-release
          git archive --format=zip --output=temp-release/module.zip HEAD

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-${{ github.sha }}
          name: Latest Build - ${{ github.sha }}
          body: |
            Automatic build from commit ${{ github.sha }}
            Commit message: ${{ github.event.head_commit.message }}
            Built on: ${{ github.event.head_commit.timestamp }}
          files: |
            module.json
            temp-release/module.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
